---
title: "LP Exercies"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


## Working Together

```{r}
library(linprog)

advert <- read.csv("https://raw.githubusercontent.com/saberry/SimOps/main/advertising_data.csv", 
                   row.names = 1)

dropDemos <- which(names(advert) == "demographic_total")

objectiveFunction <- as.matrix(advert["cost", -c(dropDemos)])

dropCost <- which(rownames(advert) == "cost")

constraintMargins <- as.matrix(advert[-c(dropCost), "demographic_total"])

constraintMatrix <- as.matrix(advert[-c(dropCost), -c(dropDemos)])

res <- solveLP(objectiveFunction, constraintMargins, constraintMatrix, 
              maximum = FALSE, const.dir = rep(">=", length(constraintMargins)))

res$opt

res$solution

res$con
```

### Keeping Track Of Variables

### Lower and Upper Bounds

```{r}
library(ROI)
library(ROI.plugin.glpk)

my_bounds <- V_bound(li = c(1:9), 
                     ui = c(1:9), 
                     lb = rep(1, 9), 
                     ub = rep())

my_constraints <- L_constraint(L = constraintMatrix, 
                               dir = rep(">=", length(constraintMargins)), 
                               rhs = constraintMargins, 
                               names = colnames(constraintMatrix))

model_create <- OP(objective = objectiveFunction, 
                   constraints = my_constraints, 
                   bounds = my_bounds, 
                   maximum = TRUE)

model_solve <- ROI_solve(model_create)

solution(model_solve, "primal")
```


## Solve this problem

$$
\begin{aligned}
\text{Maximize:}\\
\text{revenue} = 20{oil} + 5.5_{flower} \\
\text{Subject to:} \\
\text{needs} = 25_{oil} + 3.5_{flower} \leq 8960 \\
\text{oil}, \text{flower} \geq 0
\end{aligned}
$$

```{r}
objectiveFunction 

constraintValues

constraintMatrix
```

### Adding Upper and Lower Bounds

Produce at least 50 grams of oil and make note of what happens.

```{r}

```

Keep your lower bound for oil, and also specify an upper bound to keep flower less than or equal to 2000. How does your solution change?

```{r}

```

