--- 
title: "Simulation and Optimization"
author: "Seth Berry"
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
documentclass: book
---

# Introduction

In a world of exciting methods, simulation and optimization sit alone. Nobody touts how these things will change humanity. Nobody discusses how these methods can solve all of the world's problems. No...those conversations are reserved for things like statistical methods, machine learning, and the almighty AI! The secret, though, is that all of these fancy techniques do not exist without simulation and optimization. 

Optimization is found in nearly every science: from nuclear medicine and biology, to electrical engineering and statistics, and beyond. While these fields are interesting on their own, our goal is to explore optimization in the context of business problem solving, with an occasional dive into how these techniques are used in techniques you learn in other courses.  

Simulation is just as fundamental to the sciences as optimization. Nearly every event that happens is bound by some type of distribution and knowing that distribution allows us to test that event. What makes simulation so much fun is that you can program a version of the real world, run that program a few thousand times, and then generate a distribution of potential outcomes. This distribution will show us how common an event might be. 

## The Story

Meet Ali. Ali graduated from an Business Analytics program on the Atlantic coast in 2019 and made a smart career choice -- accepting an offer to work as an analyst in the cannabis industry. The global cannabis industry has seen explosive growth during the last several years (topping 9 billion in 2020 and has a project compound annual growth rate of ~26% in America alone). While some of Ali's classmates (and family) questioned the decision, it was clear that it was an industry in need of some real analytics and Ali saw a real path towards making a difference for a business (after all, most people can't make a real difference in FAANGM). The Canadian cannabis industry has nearly a decade of maturity over the American cannabis industry, and American companies are looking to cover some of that lost ground. To that end, American companies are hiring people from all of the world to create the strongest possible teams. With diverse backgrounds and experiences, the general hope is that teams will function at the highest possible levels.

Ali belonged to a team with 3 other analysts: Alex, Jun, and Shashi. Ali was the youngest and least experienced of the entire group. What Ali lacked in experience, was more than made up by technical prowess. What Ali didn't know is that the analytics world has a dark secret. Throughout Ali's education, Python and R were touted as the most important languages in the world -- they are, after all, where all of the exciting work happens. What Ali found, though, was that business analytics really runs on Excel and various add-ins. 

Ali had a goal: to become the most valuable member of the team. Ali decided to take on anything the organization needed. It seemed like a good idea at first, but Ali found out that the Business Analytics program didn't really offer the proper preparation for what was to come.